simplemooc/courses/urls.py
from django.contrib import admin
from django.urls import include, path
from . import views

urlpatterns = [
    path('', views.courses, name='index'),
    path('<slug:slug>', views.detail, name='detail'),
    path('<slug:slug>/enroll/', views.enrollment, name='enrollment'),
    path('<slug:slug>/enroll/cancel', views.undo_enrollment, name='undo_enrollment'),
    path('<slug:slug>/announcements/', views.announcements, name='announcements'),
    path('<slug:slug>/announcements/<pk>/', views.show_announcement, name='show_announcement'),
    path('<slug:slug>/lessons/', views.lessons, name='lessons'),
    path('<slug:slug>/lesson/<pk>/', views.lesson, name='lesson'),
    path('<slug:slug>/materials/<pk>/', views.material, name='material'),
]

simplemooc/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

from simplemooc.core import urls
from simplemooc.courses import urls as courses_urls
from simplemooc.accounts import urls as accounts_urls
from simplemooc.forum import urls as forums_urls

admin.autodiscover()

urlpatterns = [
    path('', include((urls, 'core'), namespace='core')),
    path('courses/', include((courses_urls, 'courses'), namespace='courses')),
    path('account/', include((accounts_urls, 'account'), namespace='account')),
    path('forum/', include((forums_urls, 'forum'), namespace='forum')),
    path('admin/', admin.site.urls),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

simplemooc/courses/models.py
from django.db import models
from django.urls import reverse
from django.conf import settings
from django.utils import timezone

from simplemooc.core.mail import send_mail_template

class CourseManager(models.Manager):
  def search(self, query):
    return self.get_queryset().filter(
      models.Q(name__icontains=query) | \
      models.Q(description__icontains=query)
    )


class Course(models.Model):
  name = models.CharField('Name', max_length=100)
  slug = models.SlugField('Shortcut')
  description = models.TextField('Description', blank=True)
  about = models.TextField('About', blank=True)
  start_date = models.DateField('Start date', null=True, blank=True)
  photo = models.ImageField(upload_to='courses/images', verbose_name='Photo', null=True, blank=True)
  created_at = models.DateTimeField('Created on', auto_now_add=True)
  updated_at = models.DateTimeField('Last updated', auto_now=True)
  objects = CourseManager()

  def __str__(self):
    return self.name

  def get_absolute_url(self):
    return "/courses/%s" % self.slug

  def release_lessons(self):
    today = timezone.now().date()
    return self.lessons.filter(release_date__gte=today)

  class Meta:
    verbose_name="Course to learn"
    verbose_name_plural="Courses to learn more"

class Enrollment(models.Model):
  STATUS_CHOICES = (
    (0, 'Pending'),
    (1, 'Approved'),
    (2, 'Canceled'),
  )

  user = models.ForeignKey(settings.AUTH_USER_MODEL, models.DO_NOTHING,
    verbose_name='User',
    related_name='enrollments'
  )
  course = models.ForeignKey(Course, models.DO_NOTHING,
    verbose_name='Course', related_name='enrollments'
  )
  status = models.IntegerField(
    'Status', choices=STATUS_CHOICES, default=1, blank=True
  )

  created_at = models.DateTimeField('Created at', auto_now_add=True)
  updated_at = models.DateTimeField('Updated at', auto_now=True)
  objects = CourseManager()
  
  def active(self):
    self.status = 1
    self.save()

  class Meta:
    verbose_name = 'Enrollment'
    verbose_name_plural = 'Enrollments'
    unique_together = (('user', 'course'),)

class Announcement(models.Model):
  course = models.ForeignKey(
    Course, models.DO_NOTHING,verbose_name='Course', related_name='announcements'
  )
  title = models.CharField('Title', max_length=100)
  content = models.TextField('Content')

  created_at = models.DateTimeField('Created at', auto_now_add=True)
  updated_at = models.DateTimeField('Updated at', auto_now=True)

  def __str__(self):
    return self.title

  class Meta:
    verbose_name = 'Announcement'
    verbose_name_plural = 'Announcements'
    ordering = ['-created_at']


class Comment(models.Model):
  announcement = models.ForeignKey(
    Announcement, models.DO_NOTHING, verbose_name='announcement', related_name='comments'
  )
  user = models.ForeignKey(settings.AUTH_USER_MODEL, models.DO_NOTHING, verbose_name='user')
  comment = models.TextField('Comment')

  created_at = models.DateTimeField('Criado em', auto_now_add=True)
  updated_at = models.DateTimeField('Atualizado em', auto_now=True)

  class Meta:
    verbose_name = 'Comment'
    verbose_name_plural = 'Comments'
    ordering = ['created_at']


def post_save_announcement(instance, created, **kwargs):
  if created:
    subject = instance.title
    context = {
      'announcement': instance
    }
    template_name = 'courses/announcement_mail.html'
    enrollments = Enrollment.objects.filter(
      course=instance.course, status=1
    )
    for enrollment in enrollments:
      recipient_list = [enrollment.user.email]
      send_mail_template(subject, template_name, context, recipient_list)

models.signals.post_save.connect(
  post_save_announcement, sender=Announcement,
  dispatch_uid='post_save_announcement'
)

class Lesson(models.Model):
  name = models.CharField('Name', max_length=100)
  description = models.TextField('Description', blank=True)
  number = models.IntegerField('Order', blank=True, default=0)
  release_date = models.DateField('Release date', blank=True, null=True)

  course = models.ForeignKey(Course, models.DO_NOTHING, verbose_name='Course', related_name='lessons')

  created_at = models.DateTimeField('Created at', auto_now_add=True)
  updated_at = models.DateTimeField('Updated at', auto_now=True)

  def __str__(self):
    return self.name

  def is_available(self):
    if self.release_date:
      today = timezone.now().date()
      return self.release_date >= today
    return False

  class Meta:
    verbose_name = 'Lesson'
    verbose_name_plural = 'Lessons'
    ordering = ['number']


class Material(models.Model):
  name = models.CharField('Name', max_length=100)
  embedded = models.TextField('Vídeo embedded', blank=True)
  file = models.FileField(upload_to='lessons/materials', blank=True, null=True)

  lesson = models.ForeignKey(Lesson, models.DO_NOTHING, verbose_name='Lesson', related_name='materials')

  def is_embedded(self):
    return bool(self.embedded)

  def __str__(self):
    return self.name

  class Meta:
    verbose_name = 'Material'
    verbose_name_plural = 'Materials'

simplemooc/courses/forms.py
from django import forms
from django.core.mail import send_mail
from django.conf import settings

from simplemooc.core.mail import send_mail_template
from .models import Comment

class ContactCourse(forms.Form):
  name = forms.CharField(label='Name', max_length=100)
  email = forms.EmailField(label='E-mail')
  message = forms.CharField(label='Message', widget=forms.Textarea)

  def send_mail(self, course):
    subject = '[%s] Contact' % course
    context = {
      'name': self.cleaned_data['name'],
      'email': self.cleaned_data['email'],
      'message': self.cleaned_data['message'],
    }
    template_name = 'courses/contact_email.html'
    send_mail_template(
      subject, template_name, context, [settings.CONTACT_EMAIL]
    )

class CommentForm(forms.ModelForm):

  class Meta:
    model = Comment
    fields = ['comment']

simplemooc/courses/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.decorators import login_required
from django.contrib import messages

from .models import Course, Enrollment, Lesson, Material
from .forms import ContactCourse, CommentForm
from .decorators import enrollment_required

def courses(request):
  courses = Course.objects.all()
  template_name = 'courses/index.html'
  context = {
    'courses': courses
  }
  return render(request, template_name, context)

def detail(request, slug):
  course = get_object_or_404(Course, slug=slug)
  context = {
    'course': course
  }
  template_name = 'courses/details.html'
  if request.method == 'POST':
    form = ContactCourse(request.POST)
    if form.is_valid():
      context['is_valid'] = True
      form.send_mail(course)
      form = ContactCourse()
  else:
    form = ContactCourse()
  
  context['form'] = form
  return render(request, template_name, context)

@login_required
def enrollment(request, slug):
  course = get_object_or_404(Course, slug=slug)
  enrollment, created = Enrollment.objects.get_or_create(
      user=request.user, course=course
  )
  if created:
    messages.success(request, 'Sucess ! Thanks for enrolling')
  else:
    messages.info(request, 'Already enrolled')

  return redirect('account:dashboard')

@login_required
def undo_enrollment(request, slug):
  course = get_object_or_404(Course, slug=slug)
  enrollment = get_object_or_404(
    Enrollment, user=request.user, course=course
  )
  if request.method == 'POST':
    enrollment.delete()
    messages.success(request, 'Your enrollment was suspended')
    return redirect('account:dashboard')
  template = 'courses/undo_enrollment.html'
  context = {
    'enrollment': enrollment,
    'course': course,
  }
  return render(request, template, context)    

@login_required
@enrollment_required
def announcements(request, slug):
  course = request.course
  template = 'courses/announcements.html'
  context = {
    'course': course,
    'announcements': course.announcements.all()
  }
  return render(request, template, context)

@login_required
@enrollment_required
def show_announcement(request, slug, pk):
  course = request.course
  announcement = get_object_or_404(course.announcements.all(), pk=pk)
  form = CommentForm(request.POST or None)
  if form.is_valid():
    comment = form.save(commit=False)
    comment.user = request.user
    comment.announcement = announcement
    comment.save()
    form = CommentForm()
    messages.success(request, 'Comment sent.')
  template = 'courses/show_announcement.html'
  context = {
    'course': course,
    'announcement': announcement,
    'form': form,
  }
  return render(request, template, context)

@login_required
@enrollment_required
def lessons(request, slug):
  course = request.course
  template = 'courses/lessons.html'
  lessons = course.release_lessons()
  if request.user.is_staff:
    lessons = course.lessons.all()
  context = {
    'course': course,
    'lessons': lessons
  }
  return render(request, template, context)

@login_required
@enrollment_required
def lesson(request, slug, pk):
  course = request.course
  lesson = get_object_or_404(Lesson, pk=pk, course=course)
  if not request.user.is_staff and not lesson.is_available():
    messages.error(request, 'This lesson is not available')
    return redirect('courses:lessons', slug=course.slug)
  template = 'courses/lesson.html'
  context = {
    'course': course,
    'lesson': lesson
  }
  return render(request, template, context)

@login_required
@enrollment_required
def material(request, slug, pk):
  course = request.course
  material = get_object_or_404(Material, pk=pk, lesson__course=course)
  lesson = material.lesson
  if not request.user.is_staff and not lesson.is_available():
    messages.error(request, 'This material is not available')
    return redirect('courses:lesson', slug=course.slug, pk=lesson.pk)
  if not material.is_embedded():
    return redirect(material.file.url)
  template = 'courses/material.html'
  context = {
    'course': course,
    'lesson': lesson,
    'material': material,
  }
  return render(request, template, context)

simplemooc/courses/templates/courses/announcement_mail.html
{{ announcement.content|linebreaks }}

simplemooc/courses/templates/courses/announcements.html
{% extends "courses/course_dashboard.html" %}

{% block dashboard_content %}
{% for announcement in announcements %}
<div class="well">
    <h2>
        <a href="{% url 'courses:show_announcement' course.slug announcement.pk %}">{{ announcement.title }}</a>
    </h2>
    {{ announcement.content|linebreaks }}
    <p>
        <a href="{% url 'courses:show_announcement' course.slug announcement.pk %}#comments">
        <i class="fa fa-comments-o"></i>
        {% with comments_count=announcement.comments.count %}
        {{ comments_count }}
        Comment{{ comments_count|pluralize }}
        {% endwith %}
        </a>
    </p>
</div>
{% empty %}
<div class="well">
    <h2>No announcements yet.</h2>
</div>
{% endfor %}
{% endblock %}

simplemooc/courses/templates/courses/contact_email.html
<p><strong>Name</strong>: {{ name }}</p>
<p><strong>E-mail</strong>: {{ email }}</p>
{{ message|linebreaks }}

simplemooc/courses/templates/courses/course_dashboard.html
{% extends "accounts/dashboard.html" %}

{% block breadcrumb %}
    {{ block.super }}
    <li>/</li>
    <li><a href="{% url 'courses:announcements' course.slug %}">{{ course }}</a></li>
{% endblock %}

{% block menu_options %}
<li class="pure-menu-heading">
    {{ course }}
</li>
<li>
    <a href="{% url 'courses:lessons' course.slug %}">
        <i class="fa fa-video-camera"></i>
        Aulas e Materiais
    </a>
</li>
<li>
    <a href="#">
        <i class="fa fa-info-circle"></i>
        Informações
    </a>
</li>
<li>
    <a href="{% url 'courses:announcements' course.slug %}">
        <i class="fa fa-envelope"></i>
        Anúncios
    </a>
</li>
<li>
    <a href="#">
        <i class="fa fa-comments"></i>
        Fórum de Dúvidas
    </a>
</li>
{{ block.super }}
{% endblock %}

simplemooc/courses/templates/courses/details.html
{% extends "base.html" %}

{% load static %}

{% block content %}
<div class="splash">
    <div class="pure-g-r">
        <div class="pure-u-1">
            <div class="l-box splash-text">
                <h1 class="splash-head">
                    {{ course }}
                </h1>
                <h2 class="splash-subhead">
                    {{ course.description }}
                </h2>
                <p>
                    <a href="{% url 'courses:enrollment' course.slug %}" class="pure-button primary-button">Subscribe</a>
                </p>
            </div>
        </div>
    </div>
</div>
<div class="pure-g-r content-ribbon">
    <div class="pure-u-2-3">
        <div class="l-box">
            <h4 class="content-subhead">About</h4>
            {{ course.about|linebreaks }}
        </div>
    </div>
    <div class="pure-u-1-3">
        <div class="l-box">
            {% if course.photo %}
            <img src="{{ course.photo.url }}" alt="" />
            {% else %}
            <img src="{% static 'img/course-image.png' %}" alt="" />
            {% endif %}
            <h4>Questions?</h4>
            <p>
                <a href="#contact" title="" class="pure-button">Message us</a>
            </p>
        </div>
    </div>
</div>

<div class="pure-g-r content-ribbon" id="contact">
    <div class="pure-u-1">
        <h3>Message us your question about the Course</h3>
        {% if is_valid %}
        <p>We'll get back to you really soon.</p>
        {% endif %}
        <form action="#contact" class="pure-form pure-form-aligned" method="post">
            {% csrf_token %}
            <fieldset>
                {% for field in form %}
                <div class="pure-control-group">
                    {{ field.label_tag }}
                    {{ field }}
                    {% if field.errors %}
                    <ul class="errorlist">
                        {% for error in field.errors %}
                        <li>{{ error }}</li>
                        {% endfor %}
                    </ul>
                    {% endif %}
                </div>
                {% endfor %}
                <div class="pure-controls">
                    <button type="submit" class="pure-button pure-button-primary">Send</button>
                </div>
            </fieldset>
        </form>
    </div>
</div>

{% endblock %}

simplemooc/courses/templates/courses/index.html
{% extends "base.html" %}

{% load static %}

{% block content %}
<div class="pure-g-r content-ribbon">
    <div class="pure-u-1">
        <div class="l-box">
            <h4 class="content-subhead">SimpleMOOC courses List</h4>
            <p>The following are the courses available</p>
        </div>
    </div>
</div>
{% for course in courses %}
<div class="pure-g-r content-ribbon">
    <div class="pure-u-1-3">
        <div class="l-box">
            <a href="{{ course.get_absolute_url }}">
            {% if course.photo %}
            <img src="{{ course.photo.url }}" alt="{{ course.name }}" />
            {% else %}
            <img src="{% static 'img/course-image.png' %}" alt="{{ course.name }}" />
            {% endif %}
            </a>
        </div>
    </div>
    <div class="pure-u-2-3">
        <div class="l-box">
            <h4 class="content-subhead"><a href="{{ course.get_absolute_url }}" title="">{{ course.name }}</a></h4>
            {{ course.description|linebreaks }}
        </div>
    </div>
</div>
{% empty %}
<div class="pure-g-r content-ribbon">
    <div class="pure-u-1">
        <div class="l-box">
            <p>No courses available.</p>
        </div>
    </div>
</div>
{% endfor %}
{% endblock %}

simplemooc/courses/templates/courses/lesson.html
{% extends "courses/course_dashboard.html" %}

{% block breadcrumb %}
    {{ block.super }}
    <li>/</li>
    <li><a href="{% url 'courses:lessons' course.slug %}">Lessons</a></li>
    <li>/</li>
    <li><a href="{% url 'courses:lesson' course.slug lesson.pk %}">{{ lesson }}</a></li>
{% endblock %}

{% block dashboard_content %}
<div class="well">
    <h2><a href="{% url 'courses:lesson' course.slug lesson.pk %}">{{ lesson }}</a></h2>
    {{ lesson.description|linebreaks }}
    <p>
        <h4>Lesson`s Materials</h4>
        <table class="pure-table full">
            <thead>
                <tr>
                    <th>
                        Name
                    </th>
                    <th>
                        Action
                    </th>
                </tr>
            </thead>
            <tbody>
                {% for material in lesson.materials.all %}
                <tr class="{% cycle '' 'pure-table-odd' %}">
                    <td>
                        {{ material }}
                    </td>
                    <td>
                        {% if material.is_embedded %}
                        <a href="{% url 'courses:material' course.slug material.pk %}">
                            <i class"fa fa-video-camera"></i>
                            Access
                        </a>
                        {% else %}
                        <a target="_blank" href="{{ material.file.url }}">
                            <i class"fa fa-download"></i>
                            Download
                        </a>
                        {% endif %}
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </p>
</div>
{% endblock %}

simplemooc/courses/templates/courses/lessons.html
{% extends "courses/course_dashboard.html" %}

{% block breadcrumb %}
    {{ block.super }}
    <li>/</li>
    <li><a href="{% url 'courses:lessons' course.slug %}">Lessons</a></li>
{% endblock %}

{% block dashboard_content %}
{% for lesson in lessons %}
<div class="well">
    <h2><a href="{% url 'courses:lesson' course.slug lesson.pk %}">{{ lesson }}</a></h2>
    <p>
        {{ lesson.description|truncatewords:'20' }}
        <br />
        <a href="{% url 'courses:lesson' course.slug lesson.pk %}" title="">
        <i class="fa fa-eye"></i>
        Access
        </a>
    </p>
</div>
{% empty %}
<div class="well">
    <h2>
        No lesson available.
    </h2>
</div>
{% endfor %}
{% endblock %}

simplemooc/courses/templates/courses/material.html
{% extends "courses/course_dashboard.html" %}

{% block breadcrumb %}
    {{ block.super }}
    <li>/</li>
    <li><a href="{% url 'courses:lessons' course.slug %}">Lessons</a></li>
    <li>/</li>
    <li><a href="{% url 'courses:lesson' course.slug lesson.pk %}">{{ lesson }}</a></li>
    <li>/</li>
    <li><a href="{% url 'courses:material' course.slug material.pk %}">{{ material }}</a></li>
{% endblock %}

{% block dashboard_content %}
<div class="well">
    <h2><a href="{% url 'courses:material' course.slug material.pk %}">{{ material }}</a></h2>
    {{ material.embedded|safe }}
    <p>
        <a href="{% url 'courses:lesson' course.slug lesson.pk %}">Back</a>
    </p>
</div>
{% endblock %}

simplemooc/courses/templates/courses/show_announcement.html
{% extends "courses/course_dashboard.html" %}

{% block breadcrumb %}
    {{ block.super }}
    <li>/</li>
    <li><a href="{% url 'courses:show_announcement' course.slug announcement.pk %}">{{ announcement }}</a></li>
{% endblock %}

{% block dashboard_content %}
    <div class="well">
        <h2>{{ announcement.title }}</h2>
        {{ announcement.content|linebreaks }}
    </div>
    <div class="well">
        <h4 id="comments">Comentários
        <a class="fright" href="#add_comment">Comment</a></h4>
        <hr />
        {% for comment in announcement.comments.all %}
        <p>
            <strong>{{ comment.user }}</strong> {{ comment.created_at|timesince }} ago: <br />
            {{ comment.comment|linebreaksbr }}
        </p>
        <hr>
        {% empty %}
        <p>
            No comments for this announcement.
        </p>
        {% endfor %}
        <form method="post" class="pure-form pure-form-stacked" id="add_comment">
            {% csrf_token %}
            <fieldset>
                {{ form.non_field_errors }}
                {% for field in form %}
                <div class="pure-control-group">
                    {{ field.label_tag }}
                    {{ field }}
                    {{ field.errors }}
                </div>
                {% endfor %}
                <div class="pure-controls">
                    <button type="submit" class="pure-button pure-button-primary">Send</button>
                </div>
            </fieldset>
        </form>
    </div>
{% endblock %}

simplemooc/courses/templates/courses/undo_enrollment.html
{% extends 'courses/course_dashboard.html' %}

{% block dashboard_content %}
<form action="" method="post">
    {% csrf_token %}
    <h3>Você deseja realmente cancelar a inscrição deste curso?</h3>
    <div class="pure-controls">
        <button type="submit" class="pure-button pure-button-primary">Confirmar</button>
        <a href="{% url 'courses:announcements' course.slug %}" class="pure-button">Voltar</a>
    </div>
</form>
{% endblock %}