simplemooc/core/urls.py
from django.contrib import admin
from django.urls import include, path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('contact/', views.contact, name='contact'),
]

simplemooc/forum/urls.py
from django.contrib import admin
from django.urls import include, path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('tag/<tag>/', views.index, name='index_tagged'),
    path('replies/<pk>/correct/', views.reply_correct, name='reply_correct'),
    path('respostas/<pk>/incorrect/', views.reply_incorrect, name='reply_incorrect'),
    path('<slug:slug>/', views.thread, name='thread'),
]

simplemooc/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

from simplemooc.core import urls
from simplemooc.courses import urls as courses_urls
from simplemooc.accounts import urls as accounts_urls
from simplemooc.forum import urls as forums_urls

admin.autodiscover()

urlpatterns = [
    path('', include((urls, 'core'), namespace='core')),
    path('courses/', include((courses_urls, 'courses'), namespace='courses')),
    path('account/', include((accounts_urls, 'account'), namespace='account')),
    path('forum/', include((forums_urls, 'forum'), namespace='forum')),
    path('admin/', admin.site.urls),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

simplemooc/forum/models.py
from django.db import models
from django.conf import settings

from taggit.managers import TaggableManager


class Thread(models.Model):

    title = models.CharField('Titlte', max_length=100)
    slug = models.SlugField('Slug', max_length=100, unique=True)
    body = models.TextField('Message')
    author = models.ForeignKey(
        settings.AUTH_USER_MODEL, models.DO_NOTHING,verbose_name='Autor', related_name='threads'
    )
    views = models.IntegerField('Views', blank=True, default=0)
    answers = models.IntegerField('Answers', blank=True, default=0)
    
    tags = TaggableManager()

    created = models.DateTimeField('Created at', auto_now_add=True)
    modified = models.DateTimeField('Updated at', auto_now=True)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return "/forum/%s" % self.slug

    class Meta:
        verbose_name = 'Topic'
        verbose_name_plural = 'Topics'
        ordering = ['-modified']


class Reply(models.Model):

    thread = models.ForeignKey(
        Thread, models.DO_NOTHING, verbose_name='Topic', related_name='replies'
    )
    reply = models.TextField('Reply')
    author = models.ForeignKey(
        settings.AUTH_USER_MODEL, models.DO_NOTHING, verbose_name='Autor', 
        related_name='replies'
    )
    correct = models.BooleanField('Correct?', blank=True, default=False)

    created = models.DateTimeField('Created at', auto_now_add=True)
    modified = models.DateTimeField('Modified at', auto_now=True)

    def __str__(self):
        return self.reply


    class Meta:
        verbose_name = 'Resposta'
        verbose_name_plural = 'Respostas'
        ordering = ['-correct', 'created']


def post_save_reply(created, instance, **kwargs):
    instance.thread.answers = instance.thread.replies.count()
    instance.thread.save()
    if instance.correct:
        instance.thread.replies.exclude(pk=instance.pk).update(
            correct=False
        )

def post_delete_reply(instance, **kwargs):
    instance.thread.answers = instance.thread.replies.count()
    instance.thread.save()

models.signals.post_save.connect(
    post_save_reply, sender=Reply, dispatch_uid='post_save_reply'
)
models.signals.post_delete.connect(
    post_delete_reply, sender=Reply, dispatch_uid='post_delete_reply'
)

simplemooc/forum/forms.py
from django import forms

from .models import Reply


class ReplyForm(forms.ModelForm):

    class Meta:
        model = Reply
        fields = ['reply']

simplemooc/forum/views.py
import json

from django.shortcuts import render, redirect, get_object_or_404
from django.views.generic import (TemplateView, View, ListView, DetailView)
from django.contrib import messages
from django.http import HttpResponse

from .models import Thread, Reply
from .forms import ReplyForm


class ForumView(ListView):

    paginate_by = 2
    template_name = 'forum/index.html'

    def get_queryset(self):
        queryset = Thread.objects.all()
        order = self.request.GET.get('order', '')
        if order == 'views':
            queryset = queryset.order_by('-views')
        elif order == 'answers':
            queryset = queryset.order_by('-answers')
        return queryset

    def get_context_data(self, **kwargs):
        context = super(ForumView, self).get_context_data(**kwargs)
        context['tags'] = Thread.tags.all()
        return context


class ThreadView(DetailView):

    model = Thread
    template_name = 'forum/thread.html'

    def get(self, request, *args, **kwargs):
        response = super(ThreadView, self).get(request, *args, **kwargs)
        if not self.request.user.is_authenticated or (self.object.author != self.request.user):
            self.object.views = self.object.views + 1
            self.object.save()
        return response

    def get_context_data(self, **kwargs):
        context = super(ThreadView, self).get_context_data(**kwargs)
        context['tags'] = Thread.tags.all()
        context['form'] = ReplyForm(self.request.POST or None)
        return context

    def post(self, request, *args, **kwargs):
        if not self.request.user.is_authenticated:
            messages.error(
                self.request, 
                'Please sign in to reply.'
            )
            return redirect(self.request.path)
        self.object = self.get_object()
        context = self.get_context_data(object=self.object)
        form = context['form']
        if form.is_valid():
            reply = form.save(commit=False)
            reply.thread = self.object
            reply.author = self.request.user
            reply.save()
            messages.success(
                self.request, 'Answer sent.'
            )
            context['form'] = ReplyForm()
        return self.render_to_response(context)


class ReplyCorrectView(View):

    correct = True

    def get(self, request, pk):
        reply = get_object_or_404(Reply, pk=pk, thread__author=request.user)
        reply.correct = self.correct
        reply.save()
        message = 'Reply updated'
        if request.is_ajax():
            data = {'success': True, 'message': message}
            return HttpResponse(json.dumps(data), mimetype='application/json')
        else:
            messages.success(request, message)
            return redirect(reply.thread.get_absolute_url())


index = ForumView.as_view()
thread = ThreadView.as_view()
reply_correct = ReplyCorrectView.as_view()
reply_incorrect = ReplyCorrectView.as_view(correct=False)

simplemooc/forum/templates/forum/index.html
{% extends "base.html" %}

{% block content %}
<div class="pure-g-r content-ribbon">
    <div class="pure-u-1">
        <ul class="breadcrumb">
            <li><a href="{% url 'core:home' %}">Home</a></li>
            <li>/</li>
            <li><a href="{% url 'forum:index' %}">Forum</a></li>
        </ul>
    </div>
    <div class="pure-u-1-3">
        <div class="pure-menu pure-menu-open">
            <ul>
                <li class="pure-menu-heading">
                    Topics
                </li>
                <li>
                    <a href="?order=">
                        <i class="fa fa-refresh"></i>
                        Most recent
                    </a>
                </li>
                <li>
                    <a href="?order=views">
                        <i class="fa fa-eye"></i>
                        More views
                    </a>
                </li>
                <li>
                    <a href="?order=answers">
                        <i class="fa fa-comments-o"></i>
                        More replies
                    </a>
                </li>
                <li class="pure-menu-heading">Tags</li>
                <li>
                    {% for tag in tags %}
                    <a href="{% url 'forum:index_tagged' tag.slug %}" class="tags">
                        <i class="fa fa-tag"></i>
                        {{ tag }}
                    </a>
                    {% endfor %}
                </li>
            </ul>
        </div>
    </div>
    <div class="pure-u-2-3">
        <div class="inner">
            {% for thread in object_list %}
            <div class="well">
                <h3><a href="{{ thread.get_absolute_url }}" title="">{{ thread.title }}</a></h3>
                <h5>
                    By {{ thread.author }} | {{ thread.answers }} reply{{ thread.answers|pluralize }} | {{ thread.views }} View{{ thread.views|pluralize }} 
                </h5>
                <p>
                    <i class="fa fa-tags"></i>
                    Tags: 
                    {% for tag in thread.tags.all %}
                    <a href="{% url 'forum:index_tagged' tag.slug %}" title="">{{ tag }}</a>{% if not forloop.last %},{% endif %}
                    {% endfor %}
                    <a class="fright" href="" title="">Updated {{ thread.modified|timesince }} ago</a>
                </p>
            </div>
            {% endfor %}
            <ul class="pagination pagination-centered">
                {% if page_obj.has_previous %}
                <li>
                    <a href="?page={{ page_obj.previous_page_number }}{% if request.GET.order %}&order={{ request.GET.order }}{% endif %}" title="">Prev</a>
                </li>
                {% endif %}
                {% for page in paginator.page_range %}
                <li{% if page == page_obj.number %} class="active"{% endif %}>
                    <a href="?page={{ page }}{% if request.GET.order %}&order={{ request.GET.order }}{% endif %}" title="">{{ page }}</a>
                </li>
                {% endfor %}
                {% if page_obj.has_next %}
                <li>
                    <a href="?page={{ page_obj.next_page_number }}{% if request.GET.order %}&order={{ request.GET.order }}{% endif %}" title="">Next</a>
                </li>
                {% endif %}
            </ul>
        </div>
    </div>
</div>
{% endblock %}

simplemooc/forum/templates/forum/thread.html
{% extends "base.html" %}

{% block content %}
<div class="pure-g-r content-ribbon">
    <div class="pure-u-1">
        <ul class="breadcrumb">
            <li><a href="{% url 'core:home' %}">Home</a></li>
            <li>/</li>
            <li><a href="{% url 'forum:index' %}">Forum</a></li>
            <li>/</li>
            <li><a href="{{ object.get_absolute_url }}">{{ object }}</a></li>
        </ul>
    </div>
    <div class="pure-u-1-3">
        <div class="pure-menu pure-menu-open">
            <ul>
                <li class="pure-menu-heading">
                    Topics
                </li>
                <li>
                    <a href="?order=">
                        <i class="fa fa-refresh"></i>
                        Most recent
                    </a>
                </li>
                <li>
                    <a href="?order=views">
                        <i class="fa fa-eye"></i>
                        More views
                    </a>
                </li>
                <li>
                    <a href="?order=answers">
                        <i class="fa fa-comments-o"></i>
                        More replies
                    </a>
                </li>
                <li class="pure-menu-heading">Tags</li>
                <li>
                    {% for tag in tags %}
                    <a href="{% url 'forum:index_tagged' tag.slug %}" class="tags">
                        <i class="fa fa-tag"></i>
                        {{ tag }}
                    </a>
                    {% endfor %}
                </li>
            </ul>
        </div>
    </div>
    <div class="pure-u-2-3">
        <div class="inner">
            <div class="well">
                <h2>{{ object }}</h2>
                {{ object.body|linebreaks }}
                <h5>
                    By {{ object.author }}
                </h5>
                <p>
                    <i class="fa fa-tags"></i>
                    {% for tag in object.tags.all %}
                    <a href="{% url 'forum:index_tagged' tag.slug %}" title="">{{ tag }}</a>{% if not forloop.last %},{% endif %}
                    {% endfor %}
                    <a class="fright" href="" title="">By {{ object.created|timesince }} ago</a>
                </p>
            </div>
            <div class="well" id="div-comments">
                <h4 id="comments">Replies
                <a class="fright" href="#add_comment">Answer</a></h4>
                {% for reply in object.replies.all %}
                <hr />
                <p>
                    <strong>{{ reply.author }}</strong> said {{ reply.created|timesince }} ago:
                    <br />
                    {{ reply.reply|linebreaksbr }}
                    <br />
                    {% if object.author == user %}
                    <a href="{% url 'forum:reply_incorrect' reply.pk %}" title="" class="pure-button button-error reply-cancel-correct-lnk{% if not reply.correct %} hidden{% endif %}">Cancel Right Awnser</a>

                    <a href="{% url 'forum:reply_correct' reply.pk %}" title="" class="pure-button button-success reply-correct-lnk{% if reply.correct %} hidden{% endif %}">Correct</a>

                    <span class="fright label-success reply-correct-msg{% if not reply.correct %} hidden{% endif %}">author answer</span>
                    <br class="reply-correct-msg{% if not reply.correct %} hidden{% endif %}" />
                    {% elif reply.correct %}
                    <span class="fright label-success">author answer</span>
                    <br />
                    {% endif %}
                </p>
                {% endfor %}
                <hr />
                <form method="post" class="pure-form pure-form-stacked" id="add_comment">
                    <fieldset>
                        {% csrf_token %}
                        {% for field in form %}
                        <div class="pure-control-group">
                            {{ field.label_tag }}
                            {{ field }}
                            {{ field.errors }}
                        </div>
                        {% endfor %}
                        <div class="pure-controls">
                            <button type="submit" class="pure-button pure-button-primary">Send</button>
                        </div>
                    </fieldset>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}

{% block scripts %}
<script type="text/javascript">
    $(".reply-cancel-correct-lnk").on("click", function(e){
        e.preventDefault();
        var $this = $(this);
        var $p = $this.closest("p");
        $.get($this.attr('href'), function(data){
            if(data.success){
                $p.find(".reply-correct-msg").addClass('hidden');
                $this.addClass('hidden');
                $p.find('.reply-correct-lnk').removeClass('hidden');
            } else {
                alert(data.message);
            }
        }, "json");
        return false;
    });
    $('.reply-correct-lnk').on('click', function(e){
        e.preventDefault();
        var $this = $(this);
        var $p = $this.closest("p");
        $.get($this.attr('href'), function(data){
            if(data.success){
                $("#div-comments .reply-correct-msg").addClass('hidden');
                $("#div-comments .reply-cancel-correct-lnk").addClass('hidden');
                $("#div-comments .reply-correct-lnk").removeClass('hidden');
                
                $p.find(".reply-correct-msg").removeClass('hidden');
                $this.addClass('hidden');
                $p.find('.reply-cancel-correct-lnk').removeClass('hidden');
            } else {
                alert(data.message)
            }
        }, 'json');
        return false;
    })
</script>
{% endblock %}